### ISSUE TITLE
Fix issue when tapping next to a Thread

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-mac#192]
**Task**

Fix issue where tapping next to the empty area next to a thread opens the thread

The click should only occur when I actually click on the threaded conversation. 

As a user, I've accidentally clicked into a threaded convo unintentionally several times.

Below in this video you see me click in the space in a non-threaded message first and then click on the area around a threaded conversation.

https://github.com/stakwork/sphinx-mac/assets/32662508/26ead001-cf6b-480d-9af2-8c7dfaa76767

**Acceptance Criteria**

- [ ] Tapping next to a Thread doesn't open the Thread
- [ ] Only tapping on the Thread opens the Thread
- [ ] Provide Video Example of functionality

**Comment by patgarner** [comment]
Please assign this one to me :)

**Comment by patgarner** [comment]
I've just committed a fix for this and issued a pull request. Below is a video demoing it, however, viewing the video it's not apparent when I'm clicking other than when I click on the thread itself. 

I'm not certain it's the best solution. The crux of the fix provides a custom NSView subclass for the CollectionViewItem's content view and then inside its mousedown reject any clicks that do not occur within a visible component of the thread. Which is achieved via IBOutlet connections to those views in the storyboard. Happy to receive feedback and make changes.


https://github.com/stakwork/sphinx-mac/assets/309928/85e1a98e-7ae0-4e8e-a4f4-90e6d848b00b
