### ISSUE TITLE
Enable clicking on template icons when sending sats

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-mac#196]
Use “test-flight” branch

**Task**

I'm currently unable to click on an icon to select when sending satoshis to another person inside the mac application. Let's enable this functionality.

https://github.com/stakwork/sphinx-mac/assets/32662508/b5ce8880-93b1-4921-a3c5-d133077d625f

### Acceptance Criteria

- [ ] Use “test-flight” branch
- [ ] I've tested locally on my desktop
- [ ] I've posted a video recording of me clicking an icon in the PR

**Comment by tomastiminskas** [comment]
You can scroll using trackpad but template icons are not clickable right now

**Comment by ecurrencyhodler** [comment]
Hmmm I'm unable to scroll using a trackpad or my mouse to see more of the convo.

**Comment by ecurrencyhodler** [comment]
So maybe a feature request is to enable clicking on template icons?

**Comment by tomastiminskas** [comment]
> So maybe a feature request is to enable clicking on template icons?

Yes, exactly

**Comment by Khaalid-oh** [comment]
👍🏽
