### ISSUE TITLE
Fix issue where scroll bar across Friends and Tribes view are both visible

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-mac#257]
Use “test-flight” branch

**Task**

When I click on the scroll bar inside the friends column, I see two scroll bars and one of them persists while the other one moves up and down.

- When in Friends view, hide Tribes Scroll
- When in Tribes view, hide Friends Scroll

https://github.com/stakwork/sphinx-mac/assets/32662508/c86e6909-4f2e-4504-8201-1129a3691b30

**Acceptance Criteria**

- [ ] Use “test-flight” branch
- [ ] Only one scroll bar when scrolling friends
- [ ] Only one scroll bar when scrolling tribes

**Comment by kapildadhich075** [comment]
hi, @ecurrencyhodler   I would like to work on this issue, can you please assign me to this?

**Comment by ecurrencyhodler** [comment]
hey @kapildadhich075. Thanks for reaching out. I've noticed you've commented on several issues asking to be assigned to them. Why don't we start off with just one issue first and then if that one goes well, we can assign you to more. 

Would you like to start off with this ticket?

**Comment by Vayras** [comment]
@ecurrencyhodler , I have recently started learning swift can I start working on this issue , since I use the app as well I would be , a nice challenge for me to work and get this done , Let me know if you can assign me to this

**Comment by ecurrencyhodler** [comment]
That would be awesome @Vayras go ahead and give this a shot.

**Comment by ecurrencyhodler** [comment]
I assigned you the bounty: https://community.sphinx.chat/bounty/847

**Comment by tomastiminskas** [comment]
Any updates on this @Vayras ? I wasn't able to reproduce the issue. I guess it's related with a specific MacOS version. But any feedback from you will be appreciated, thanks

**Comment by Vayras** [comment]
> Any updates on this @Vayras ? I wasn't able to reproduce the issue. I guess it's related with a specific MacOS version. But any feedback from you will be appreciated, thanks

Hey @tomastiminskas apparently what I have been told and seen myself is this was fixed the same day as I was assigned, by a guest developer, I couldn't reproduce the issue so I assumed this was closed
