### ISSUE TITLE
Join Tribes Window Too Large

### ISSUE THREAD

**Issue by uncleJim21** [stakwork/sphinx-mac#95]
Use “test-flight” branch

**Task**

Fix issue where Join Tribes Window is too large.

![image](https://github.com/stakwork/sphinx-mac/assets/96802642/cdf46b62-ac3f-4070-945b-f57f8b5892bc)

Steps to recreate:

- Go to Tribes Web Page - [here](https://tribes.sphinx.chat/)
- Click Join Button on a Tribe
- Observe that window takes up whole page and then some

**Fix**

- WIndow height should be smaller
- Content of Join tribe view should be scrollable
- `Join Tribe` button should always be glued to the bottom at all times

**Acceptance Criteria**

- [ ] Use “test-flight” branch
- [ ] Smaller Join tribes Window
- [ ] Scrollable content
- [ ] Provide a Video recording of fix

**Comment by tomastiminskas** [comment]
Content of Join tribe view should be scrollable

**Comment by patgarner** [comment]
Please assign this one to me :)

**Comment by patgarner** [comment]
I've pushed a fix, but I now realize the instructions say that the Join Tribe button should always be glued to the bottom at all times. For clarity, does this mean you want the view content to scroll behind the button?

https://github.com/stakwork/sphinx-mac/assets/309928/da990b66-8793-4483-84b0-b1fc5ed32cc2

**Comment by tomsmith8** [comment]
In order to keep Join Tribe visible, making the content scrollable is the only option with the current design format. Looks good to me!

**Comment by patgarner** [comment]
All the programmatic UI has been moved to the storyboard and a clipview subclass was added to enhance the positioning of the scrollview content when resizing the view/window. Including another demo here (for posterity?) which uses a bugus tribe description to enhance the demonstration of the view layout.  

https://github.com/stakwork/sphinx-mac/assets/309928/6df2a188-b0bf-4d59-9550-eb3b3071d4f1

**Comment by tomastiminskas** [comment]
Perfect, thanks @patgarner . I will review and merge during the day.
